#!/usr/bin/env python3
"""
DFTcu Reference Data Extraction Tool (Mock/Template)
针对 SiC 体系从 QE 提取带索引的标准数据。
"""

import numpy as np


def extract_vloc_indexed(qe_vloc_file, nr):
    """
    从 QE 导出文件提取带 (ix, iy, iz) 索引的势场。
    """
    # 假设 qe_vloc 是一个 3D 数组
    vloc = np.load(qe_vloc_file)  # 示例
    indexed_data = []
    for ix in range(nr[0]):
        for iy in range(nr[1]):
            for iz in range(nr[2]):
                val = vloc[ix, iy, iz]
                indexed_data.append(f"{ix} {iy} {iz} {val:.16e}")
    return indexed_data


def extract_psi_indexed(qe_wfc_file, miller_indices):
    """
    从 QE 提取带 Miller 索引 (h, k, l) 的波函数系数。
    """
    wfc = np.load(qe_wfc_file)  # 示例
    indexed_data = []
    for i, (h, k, l) in enumerate(miller_indices):
        re, im = wfc[i].real, wfc[i].imag
        indexed_data.append(f"{h} {k} {l} {re:.16e} {im:.16e}")
    return indexed_data


if __name__ == "__main__":
    print("# Generated by extract_qe_indexed.py")
    print("# SiC Zinc-blende 16x16x16")
    # 实际逻辑应调用 qepy 或解析 QE XML/Binary 文件
    print("0 0 0 -1.2345678901234567e+00")
